/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author DM3-1-03
 */
public class addCompetitionPrueba extends javax.swing.JFrame {

    /**
     * Creates new form addDiscipline
     */
    public addCompetitionPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_name = new javax.swing.JLabel();
        jLabel_description = new javax.swing.JLabel();
        jLabel_location = new javax.swing.JLabel();
        jLabel_startDate = new javax.swing.JLabel();
        jButton_send = new javax.swing.JButton();
        jTextField_name = new javax.swing.JTextField();
        jTextField_description = new javax.swing.JTextField();
        jTextField_location = new javax.swing.JTextField();
        jTextField_startDate = new javax.swing.JTextField();
        jLabel_endDate = new javax.swing.JLabel();
        jTextField_endDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel_name.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_name.setText("Name:");

        jLabel_description.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_description.setText("Description:");

        jLabel_location.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_location.setText("Location:");

        jLabel_startDate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_startDate.setText("Start date:");

        jButton_send.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_send.setText("Send");

        jLabel_endDate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel_endDate.setText("End date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_name)
                    .addComponent(jLabel_description)
                    .addComponent(jLabel_location)
                    .addComponent(jLabel_startDate)
                    .addComponent(jLabel_endDate))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_name)
                    .addComponent(jTextField_description)
                    .addComponent(jTextField_location)
                    .addComponent(jTextField_startDate)
                    .addComponent(jTextField_endDate, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_send, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_name)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel_description))
                    .addComponent(jTextField_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_location)
                    .addComponent(jTextField_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_startDate)
                    .addComponent(jTextField_startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_endDate))
                .addGap(35, 35, 35)
                .addComponent(jButton_send, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_send;
    private javax.swing.JLabel jLabel_description;
    private javax.swing.JLabel jLabel_endDate;
    private javax.swing.JLabel jLabel_location;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_startDate;
    public javax.swing.JTextField jTextField_description;
    public javax.swing.JTextField jTextField_endDate;
    public javax.swing.JTextField jTextField_location;
    public javax.swing.JTextField jTextField_name;
    public javax.swing.JTextField jTextField_startDate;
    // End of variables declaration//GEN-END:variables
}
